### ISSUE TITLE
How can you get the offset values？

### ISSUE THREAD

**Issue by wuguangbin1230** [CTTC/Kinect-v2-Tutorial#1]
Hello, 
In your image_to_world.py, how did you get the  x_offset,  y_offset, z_offset values?

**Comment by taochenshh** [comment]
Sorry for the confusion. I wrote these codes really long time ago, and I did not add any comments. I think these numbers come from the calibration results.

**Comment by wuguangbin1230** [comment]
Firstly, Thank you for your reply!

I look for the z-offset values, in Kinect-v2-Tutorial/035623243247/ , but I could not find the values 0.006, which was discribed z_offset = 0.006 in https://github.com/taochenshh/Kinect-v2-Tutorial/blob/master/image_to_world.py

**Comment by taochenshh** [comment]
Thanks for your reminder. I remembered now that those numbers are just for compensation. That's to say, you can run the program, and see if x, y, z axes have any constant offsets. If so, manually adjust these numbers so that the errors are minimized.
